name: Pull Request



on:
  pull_request:
    branches:
    - master



env:
  AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
  SBOM_FILENAME: package-sbom



permissions:
  actions: read
  id-token: write
  contents: read
  packages: read



jobs:
  cancel_previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-22.04
    timeout-minutes: 3

    steps:
      - uses: ydataai/cancel-workflow-action@0.7.0
        with:
          ignore_sha: true
          access_token: ${{ github.token }}

  validate:
    name: Validate
    runs-on: ubuntu-22.04

    needs:
    - cancel_previous

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - uses: fwal/setup-swift@v2
      with:
        swift-version: "5.7"

    - name: Package Resolve
      run: swift package resolve

    - name: Build CloudFormation for test
      run: swift build --product CloudFormation

    - name: Build Command for test
      run: swift build --product Command


  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Create SBOM
      uses: anchore/sbom-action@v0.17.0
      with:
        upload-artifact-retention: 1
        format: cyclonedx-json
        output-file: ${{ env.SBOM_FILENAME }}.cyclonedx.json

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_S3_SBOMS_ROLE_ARN }}
        aws-region: ${{ env.AWS_S3_REGION }}

    - name: Copy SBOM to S3
      run: |
        aws s3 cp ${{ env.SBOM_FILENAME }}.cyclonedx.json s3://repos-sboms/${{ github.event.repository.name }}/${{ env.SBOM_FILENAME }}.cyclonedx.json
