name: Released



on:
  release:
    types:
    - released



env:
  DOCKERHUB_REGISTRY: ydata
  DOCKER_REPOSITORY_COMMAND: aws-asg-tags-command
  DOCKER_REPOSITORY_LAMBDA: aws-asg-tags-lambda



permissions:
  id-token: write
  contents: read
  packages: write



jobs:
  cancel_previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-20.04
    timeout-minutes: 3

    steps:
      - uses: ydataai/cancel-workflow-action@0.7.0-fix
        with:
          ignore_sha: true
          access_token: ${{ github.token }}


  prepare:
    name: Prepare
    runs-on: ubuntu-20.04

    needs:
    - cancel_previous

    outputs:
      build_number: ${{ steps.short_sha.outputs.value }}
      new_version: ${{ steps.new_version.outputs.value }}
      old_version: ${{ steps.old_version.outputs.value }}

    steps:
    - name: Version
      id: new_version
      run: echo "value=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git Short sha
      id: short_sha
      run: echo "value=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Extract original version
      id: old_version
      run: echo "value=$(git tag | grep ${{ steps.short_sha.outputs.value }} | sed -r 's|([0-9].[0-9].[0-9]).*|\1|g')" >> $GITHUB_OUTPUT


  docker-tag-command:
    name: Docker Tag and Push COMMAND version
    runs-on: ubuntu-20.04

    needs:
    - prepare

    steps:
    - name: Login to Dockerhub Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker tag and push
      env:
        SOURCE: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKER_REPOSITORY_COMMAND }}:${{ needs.prepare.outputs.old_version }}.${{ needs.prepare.outputs.build_number }}
        DESTINATION_DOCKERHUB: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKER_REPOSITORY_COMMAND }}:${{ needs.prepare.outputs.new_version }}
      run: |
        docker pull $SOURCE
        docker tag $SOURCE $DESTINATION_DOCKERHUB
        docker push $DESTINATION_DOCKERHUB


  docker-tag-lambda:
    name: Docker Tag and Push LAMBDA version
    runs-on: ubuntu-20.04

    needs:
    - prepare

    steps:
    - name: Login to Dockerhub Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker tag and push
      env:
        SOURCE: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKER_REPOSITORY_LAMBDA }}:${{ needs.prepare.outputs.old_version }}.${{ needs.prepare.outputs.build_number }}
        DESTINATION_DOCKERHUB: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKER_REPOSITORY_LAMBDA }}:${{ needs.prepare.outputs.new_version }}
      run: |
        docker pull $SOURCE
        docker tag $SOURCE $DESTINATION_DOCKERHUB
        docker push $DESTINATION_DOCKERHUB


  update-manifests:
    name: Update AWS Marketplace
    runs-on: ubuntu-20.04

    needs:
    - prepare
    - docker-tag-command

    env:
      COMPONENT: ASG_TAGS_VERSION

    steps:
    - name: Checkout AWS Marketplace repo
      uses: actions/checkout@v3
      with:
        repository: ydataai/aws-marketplace
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Update aws-marketplace
      run: echo ${{ needs.prepare.outputs.new_version }} > ${{ env.COMPONENT }}

    - name: Commit and push image update into manifests repo
      env:
        VERSION: ${{ needs.prepare.outputs.new_version }}
      run: |
        git config user.email "azory@ydata.ai"
        git config user.name "Azory YData Bot"
        git add ${{ env.COMPONENT }}
        git commit -a -m "chore(bump): [CI] [PROD] bump ${{ env.COMPONENT }} to $VERSION"
        git push origin master
